### ISSUE TITLE
Create background worker for address geocoding

### ISSUE THREAD

**Issue by astar26** [Lev-Echad/levechad-backend#309] opened 2020-04-16 21:35 UTC
**Related component**: client

## Description
Create a background worker for address to coordinate translation.

----
### Prerequisites
_[Make sure you've done the following before posting your issue:]_
* [ ] I have filled in the correct labels (fill at least one of bug/enhancement)
* [ ] I have searched for duplicate issues and found none
* [ ] My issue is phrased as a task - it's clear what needs to be done here.

**Comment by stavlocker** [comment] 2020-04-16 21:37
Duplicate of #272

**Closed by stavlocker** 2020-04-16 21:37 UTC
Labels: Epic, enhancement
